//=require 'page/page.js'
//=require 'jquery/dist/jquery.js'
//=require 'bootstrap/dist/js/bootstrap.js'
//=require 'firebase/firebase.js'
//=require 'moment/moment.js'
//=require 'handlebars/dist/handlebars.runtime.js'
//=require 'caman-dist-only/dist/caman.full.js'
